#!/usr/bin/python3
import sys
import math


def prim_factorize(num):
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0 and isprime(i) and isprime(num / i):
            x = int(num / i)
            print("{}={}*{}".format(num, x, i))
            return


def isprime(n):
    if n <= 1:
        return False
    else:
        for i in range(2, int(math.sqrt(n) + 1)):
            if n % i == 0:
                return False
        return True


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit()
    try:
        with open(sys.argv[1], "r") as file:
            read = file.read().splitlines()
    except FileNotFoundError:
        print("file not found")
        exit()
    for line in read:
        prim_factorize(int(line))
